### ISSUE TITLE
make the environment's deps explicit in the README

### ISSUE THREAD

**Issue by RPierini** [navarrothiago/upf-bpf#60]
Hello!

I tried to blindly follow the instructions in the First Steps part of the README to set up the environment, and there were some issues that may be interesting to review:

1. It's necessary to install at least the "Make" and "Docker" packages (seems obvious, but maybe not to someone new) to make it possible to run the commands and build the containers
2. If the files that's copied in the docker/build_docker  script doesn't exists, the script fails with an errorn1. I believe the RSA keys are important for the build (I didn't analyze the script deeply), but the .gitconfig and ssh_config may be optional. Isn't it better to test if those files exists and add some notes or external link in the docs about how to generate them?

I'm not used to Github, but if I can help with those, please let me know :)

**Comment by navarrothiago** [comment]
@RPierini Thanks to point this. Absolutely. I know that that are a lot of things to improve. I would love to see an PR with this change. Let me know if you need any help. Feel free to reach me on discord server.

**Comment by RPierini** [comment]
> @RPierini Thanks to point this. Absolutely. I know that that are a lot of things to improve. I would love to see an PR with this change. Let me know if you need any help. Feel free to reach me on discord server.

Thanks! I'll do my best to try and solve this. I'll get in touch through Discord later too! As I said, i'm not used to github, and I started reading about the SSH and GPG keys management in GH and I think I got why you're sending those files to the container at build time. In the README it's said that the private key would be sent within the container, but maybe if the build was multi-stage like described [here](https://vsupalov.com/cache-docker-build-dependencies-without-volume-mounting/), then the key file would be in the intermediate build, but not inside the final image.
Other point is that it's hardcoded in the script to use a RSA key, but it seems that [GH started to recommend ed25519 keys for key authentication](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). I'll try to modify the build_docker script for it to ask which key from the user's .ssh folder to use or to use a priority criteria (like ed25519 > dsa > rsa) to choose the key file to use.

I'll try to address those points in the PR, is that ok?

**Comment by RPierini** [comment]
> > @RPierini Thanks to point this. Absolutely. I know that that are a lot of things to improve. I would love to see an PR with this change. Let me know if you need any help. Feel free to reach me on discord server.
> [...]
> Other point is that it's hardcoded in the script to use a RSA key, but it seems that [GH started to recommend ed25519 keys for key authentication](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). I'll try to modify the build_docker script for it to ask which key from the user's .ssh folder to use or to use a priority criteria (like ed25519 > dsa > rsa) to choose the key file to use.

Ok, about this part of my last comment, I just saw the "env.sh" file in the script and it's configurations... I'll address it in the PR for the README file for reference 😉

**Comment by RPierini** [comment]
PR #65 solved this issue
