### ISSUE TITLE
GTP packet generation

### ISSUE THREAD

**Issue by RKR-11** [navarrothiago/upf-bpf#68]
Hi,
Can I use the run.py file itself to generate the gtp packets or do I need to setup the Upf-bpf and run according to Doc.

https://github.com/navarrothiago/upf-bpf/blob/2b6679f7a5dca162fa0eb65117a82643ae30d103/tests/trex/test_cases/run.py#L29-L35

Iam new to this if there is any way to generate gtp packets directly from run.py can you please help me with this. what are the args to be passed while running.

**Comment by navarrothiago** [comment]
@RKR-11, sorry for the delay. The script was created to test using this setup:  ![](https://raw.githubusercontent.com/navarrothiago/upf-bpf/master/img/setup-performance-evaluation.svg)

I suggest you to check the client snippet code avaiable in [Trex Stateless API docs](https://trex-tgn.cisco.com/trex/doc/cp_stl_docs/api/client_code.html#stlclient-snippet).
